blueprint:
  name: Activate Lights, Colour and Dim
  domain: automation
  input:
    trigger:
      name: Trigger
      description: Select entity(ies) to trigger this automation
      selector:
        entity:
          filter:
            domain: binary_sensor
    lights_config:
      name: Lights Config
      description: Select all lights to control with this automation
      all_lights:
        name: Shit
        selector:
          target:
            entity:
              domain: light