blueprint:
  homeassistant:
    min_version: 2024.6.0
  name: Activate lights, set colour and dimming
  domain: automation
  input:
    trigger:
      name: Trigger
      description: Select entity(ies) to trigger this automation
      selector:
        entity:
          multiple: true
          filter:
            domain: binary_sensor
    set_lights:
      name: Choose Lights
      input:
        day_lights:
          name: Daytime Lights
          selector:
            target:
              entity:
                domain: light
        night_lights:
          name: Nighttime Lights
          selector:
            target:
              entity:
                domain: light
    set_times:
      name: Set Times
      input:
        day_time:
          name: Daytime start
          default: 05:30:00
          selector:
            time:
        night_time:
          name: Nighttime start
          default: 20:30:00
          selector:
            time: