blueprint:
  name: Activate Lights, Colour and Dim
  description: >
    # 💡 Activate Lights, set colour temperature according to sun's position and set on level depending on time-of-day.
    
    **Version: 0.1**
    
    <details>
    <summary><b>The Automation Process:</b> 👈</summary>
      
      - **Trigger:**
        - Some words.
        - Some more words.
    </details>
    domain: automation
  input:
    triggers:
      name: "Trigger"
      icon: mdi:cog-outline
      collapsed: true
      input:
          lights_on_trigger:
          name: Lights on trigger
          description: Select entity(ies) to trigger this automation.
          default: []
          selector:
            entity:
              filter:
                domain:
                  - binary_sensor
              multiple: true
    target_lights:
      name: "Lights"
      icon: mdi:lightbulb-outline
      collapsed: true
      input:
        all_lights:
          name: All Lights
          description: Select all lights to control with this automation.
          default: []
          selector:
            target:
              entity:
                domain:
                  - light
    nighttime_light:
      name: "Nighttime Light"
      icon: mdi:lightbulb-night-outline
      collapsed: true
      input:
      description: Select light(s) to only activate at nighttime.
      default: []
      selector:
        target:
          entity:
            domain:
              - light
    actions:
    - choose:
        - conditions:
            - condition: time
              after: "20:30:00"
              before: "06:00:00"
          sequence:
            - action: light.turn_on
              metadata: {}
              data:
                transition: 3
                brightness_pct: 5
              target:
                device_id: 493df3c5e3fe57dd05c2197901401431
        - conditions:
            - condition: time
              after: "06:00:00"
              before: "20:30:00"
          sequence:
            - action: light.turn_on
              metadata: {}
              data:
                transition: 2
                brightness_pct: 100
              target:
                area_id: en_suite
