blueprint:
  name: Activate Lights, Colour and Dim
  description: >
    # 💡 Activate Lights, set colour temperature according to sun's position and set on level depending on time-of-day.
    
    **Version: 0.1**
    
    <details>
    <summary><b>The Automation Process:</b> 👈</summary>
      
      - **Trigger:**
        - Some words.
        - Some more words.
    </details>
    domain: automation
  input:
    trigger:
      name: "Trigger *"
      icon: mdi:cog-outline
      collapsed: true
      input:
