blueprint:
  name: Activate Lights, Colour and Dim
  domain: automation
  input:
    triggers:
      name: Trigger
      icon: mdi:cog-outline
      description: Select entity(ies) to trigger this automation
      selector:
        entity:
          filter:
            domain: binary_sensor
            multiple: true
    lights_config:
      name: Lights Config
      icon: mdi:lightbulb-outline
      description: Select all lights to control with this automation
      selector:
        entity:
          filter:
            domain: light
            multiple: true