blueprint:
  homeassistant:
    min_version: 2024.6.0
  name: Activate lights, set colour and dimming
  domain: automation
  input:
    trigger:
      name: Trigger
      description: Select entity(ies) to trigger this automation
      selector:
        entity:
          filter:
            domain: binary_sensor
      multiple: true
    day_lights:
      name: Daytime Lights
      description: Select daytime lights to control with this automation
      selector:
        area:
          filter:
            domain: light
    night_lights:
      name: Nighttime Lights
      description: Select nighttime lights to control with this automation
      selector:
        area:
          filter:
            domain: light
    set_times:
      name: Set Times
      input:
        day_time:
          name: Daytime start
          selector:
            time:
        night_time:
          name: Nighttime start
          selector:
            time: