blueprint:
  name: Activate Lights, Colour and Dim
  description: >
    # 💡 Activate Lights, set colour temperature according to sun's position and set on level depending on time-of-day.
    
    **Version: 0.1**
    
    <details>
    <summary><b>A summary:</b> Hi this is a thing</summary>
      
      - **Trigger:**
        - Some words.
        - Some more words.
    </details>
  domain: automation
  input:
    triggers:
      name: Trigger
      icon: mdi:cog-outline
      input:
        lights_on_trigger:
        name: Lights on trigger
        description: Select entity(ies) to trigger this automation
        selector:
          entity:
            filter:
              domain:
                - binary_sensor
              multiple: true
    lights_config:
      input:
      name: Lights Config
      icon: mdi:lightbulb-outline
      input:
        all_lights:
          name: All Lights
          description: Select all lights to control with this automation
          input:
            selector:
              target:
                entity:
                  domain:
                    - light