blueprint:
  homeassistant:
    min_version: 2024.6.0
  name: Activate lights, set colour and dimming
  domain: automation
  input:
    trigger:
      name: Trigger
      description: Select entity(ies) to trigger this automation
      selector:
        device:
          multiple: true
          entity:
            integration: zha
    set_lights:
      name: Choose Lights
      input:
        day_lights:
          name: Daytime Lights
          description: Select the lights to switch on during the day
          selector:
            target:
              entity:
                domain: light
        night_lights:
          name: Nighttime Lights
          description: Select the lights to swtich on during the night
          selector:
            target:
              entity:
                domain: light
    set_times:
      name: Set Times (Defaults to daytime starting at 05:30 and finishing at 20:30)
      collapsed: true
      input:
        day_time:
          name: Daytime start
          description: Choose when daytime begins
          default: 05:30:00
          selector:
            time:
        night_time:
          name: Nighttime start
          description: Choose when nighttime begins
          default: 20:30:00
          selector:
            time:
    set_colour:
      name: Set Colour Temperature
      collapsed: true
      input:
        min_colour_temp:
          name: Coolest Colour Temperature
          description: The most blue colour your bulbs will be set to
          default: 4000
          selector:
            color_temp:
              min: 1500
              max: 7000
              unit: kelvin
        max_colour_temp:
          name: Warmest Colour Temperature
          description: The most yellow colour your bulbs will be set to
          default: 2202
          selector:
            color_temp:
              min: 1500
              max: 7000
              unit: kelvin
    brightness:
      name: Brightness
      collapsed: true
      input:
        daytime_brightness:
          name: Daytime Brightness
          description: The brightness to set bulbs to during the day
          default: 100
          selector:
            number:
              min: 0
              max: 100
              mode: slider
        nighttime_brightness:
          name: Nighttime Brightness
          description: The brightness to set bulbs to at night
          default: 5
          selector:
            number:
              min: 0
              max: 100
              mode: slider