blueprint:
  name: Activate Lights, Colour and Dim
  domain: automation
  input:
    trigger:
      name: Trigger
      description: Select entity(ies) to trigger this automation
      selector:
        entity:
          filter:
            domain: binary_sensor
    day_lights:
      name: Daytime Lights
      description: Select daytime lights to control with this automation
      selector:
        entity:
          filter:
            domain: light
    night_lights:
      name: Nighttime Lights
      description: Select nighttime lights to control with this automation
      selector:
        entity:
          filter:
            domain: light